repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-mutable
          - flake8-print
          - flake8-simplify
          - flake8-pyproject
        exclude: settings.py
        id: flake8

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.6.0
    hooks:
      - args:
          - -f
          - requirements.txt
          - -o
          - requirements.txt
          - --without-hashes
        id: poetry-export
